version: '3'
services:
  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    volumes:
      - ./www:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./www:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=phpServerName
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    user: 1000:1000
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./www:/var/www/html
      - composer:/root/.composer/cache
    depends_on:
      - mysql
    tty: true
volumes:
  mysql:
  composer:
