version: '3'
services:
  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    volumes:
      - ./www:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./www:/var/www/html
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8085:8080
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/db:/var/lib/mysql
    user: 1000:1000
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
